### PR TITLE
Release refresh token only if offline_access scope is used

### LINKED ISSUE #154: Support offline_access scope
From core spec: https://openid.net/specs/openid-connect-core-1_0.html#OfflineAccess

> offline_access
        OPTIONAL. This scope value requests that an OAuth 2.0 Refresh Token be issued that can be used to obtain an Access Token that grants access to the End-User's UserInfo Endpoint even when the End-User is not present (not logged in).

### PR DESCRIPTION
**Pull request by cicnavi**
Note: client has to have 'offline_access' scope registered. 

Fixes #154
Fixes #187

### CODE REVIEW

**Comment by pradtke** [comment]
I think this looks good.  I was wondering how to check if any apps are currently making use of refresh tokens with out requesting offline scope (e.g. will I break any apps when I deploy this update).  I couldn't see anything that would appear in the logs for a refresh token. Do you have any ideas?

**Review by pradtke — APPROVED** [review]

**Comment by pradtke** [comment]
I'll try to add a patch to our deployment to log current refresh token usage. I think once we have some data it will be easier to decide the impact.  I suppose a 3rd option is to make it a configuration option 'alwaysIssueRefreshToken' and then when people upgrade they can decide what to do.

**Comment by cicnavi** [comment]
I think the default option is a good idea! This way we can still release v2 without problems. I'll try to implement it on Monday.

**Comment by cicnavi** [comment]
Please check the new config option for refresh token release, which is true by default. Basically this means no change in behavior regarding refresh token release comparing with v1. However, we have a possibility to do it in a spec compliant way by setting the option to false...

**Comment by pradtke** [comment]
Thanks @cicnavi . I'll try to upgrade out internal environment soon.

**Pull request merged**
