### PR TITLE
Fix admin-clients link

### PR DESCRIPTION
**Pull request by Pyrex-FWI**
image

### CODE REVIEW

**Review by pradtke — COMMENTED** [review]
Thanks @Pyrex-FWI  for the change.

**Comment by pradtke** [comment]
Hmm, I'm not sure why github won't run the unit tests, etc was part of the PR. I can't do the merge until they run.

**Review by tvdijen — APPROVED** [review]

**Comment by tvdijen** [comment]
It never triggered Actions, so I can't re-run the tests either.. I was hoping that approving the change would trigger things, but that didn't work out either.. I can merge it without running the tests though.. @pradtke ?

**Comment by pradtke** [comment]
> . I can merge it without running the tests though.. @pradtke ?

Yes please. Thanks @tvdijen

**Comment by pradtke** [comment]
hmm, and of course all the checks ran after I replied to your message.  I'll do the merge.

**Comment by tvdijen** [comment]
Haha, we got Github on it's knees!

**Pull request merged**
